version: '2.0'

networks:
  qbiknet:
    external:
      name: qbiknet

services:
  redmine:
    image: redmine
    restart: always
    ports:
      - 3000:3000
    environment:
    -  REDMINE_DB_MYSQL
    -  REDMINE_DB_PASSWORD
    networks:
      qbiknet:
        aliases:
          - redmine.qbik

  db:
    image: mysql:5.7
    restart: always
    environment:
    -  MYSQL_ROOT_PASSWORD
    -  MYSQL_DATABASE
    volumes:
      - './postgres/:/var/lib/postgresql/data'
    networks:
      qbiknet:
        aliases:
          - redmine_pg.qbik
