version: '2'

networks:
  qbiknet:
    external:
      name: qbiknet

services:
  owncloud:
    build: ./build
    image: owncloud-ldap
    restart: on-failure:10
    container_name: owncloud
    links:
    - oc_postgres:oc_postgres
#    ports:
#    - 8080:80
    volumes:
    - './data/apps/:/var/www/html/apps'
    - './data/config/:/var/www/html/config'
    - './data/data/:/var/www/html/data'
    - './data/.user.ini:/var/www/html/.user.ini'
    - '/raid/doc/:/doc'
    - '/raid/1c/:/1c'
    - '/raid/pub/:/pub'
    networks:
      qbiknet:
        aliases:
          - owncloud_web.qbik

  oc_postgres:
    image: postgres:9.5
    container_name: own_postgres
    restart: on-failure:10
    environment:
    -  POSTGRES_PASSWORD
    -  POSTGRES_USER
    volumes:
      - './postgres/data/:/var/lib/postgresql/data'
    networks:
      qbiknet:
        aliases:
          - own_pgpostgres.qbik
