version: '2'

networks:
  qbiknet:
    external:
      name: qbiknet

services:
  rabbitmq:
    container_name: "rabbitmq"
    restart: on-failure:10
    image: rabbitmq:management
    environment:
    - RABBITMQ_DEFAULT_USER
    - RABBITMQ_DEFAULT_PASS
    ports:
    - "4369:4369"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"
    volumes:
    - "./data/:/var/lib/rabbitmq/"
    networks:
      qbiknet:
        aliases:
          - rabbitmq.qbik
