version: '2'

networks:
  qbiknet:
    external:
      name: qbiknet

services:
  nginx:
    image: nginx
    container_name: 'nginx'
    restart: on-failure:10
    ports:
      - 80:80
      - 443:443
    volumes:
      - './nginx/www:/var/www/'
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './nginx/ssl/:/etc/nginx/ssl'
      - '../nextcloud/data/core/:/var/www/html/core'

    networks:
      qbiknet:
        aliases:
          - nginx.qbik
